language: php
php:
  - 7.1

services:
  - docker

before_script:
  - ls
  - cd ./service && composer self-update && cd ../
  - cd ./service && composer install  && cd ../

script:
  - ./service/vendor/bin/phpunit